server:
  port: 0
spring:
  application:
    name: test1

eureka:
  client:
    service-url:
      defaultZone: http://locallhost:8761/eureka
  instance:
 #   ip-address: 192.168.0.12
   prefer-ip-address: true
   instance-id: ${spring.application.name}:${random.uuid}


